"""
reward.py
=========
Privileged evaluator (E+) for PF-OPSD Stage 2.

──────────────────────────────────────────────────────────────────────
ARCHITECTURE CLARIFICATION (critical for understanding OPSD)
──────────────────────────────────────────────────────────────────────

PF-OPSD is a form of On-Policy Self-Distillation (OPSD).
"Self" means the teacher and student are THE SAME model (π_θ):

  Student π_θ   — runs WITHOUT privileged context:
                  input = (anchor, rollout_v̂, question, options)
                  No ground-truth future v*, no correct answer y*.

  Teacher π_θ+  — IS THE SAME MODEL, but runs WITH privileged context:
                  input = (anchor, rollout_v̂, future_v*, question, options, y*)
                  Because it sees v* and y*, it makes better decisions.

The "distillation" is: train π_θ (student view) to match the distribution
that π_θ (teacher / privileged view) produces at each decision node.

P_t+(a) = π_θ(a | c_t+, h_t^s)  — same model weights, privileged inputs.

──────────────────────────────────────────────────────────────────────
ROLE OF Qwen3.6-27B
──────────────────────────────────────────────────────────────────────

Qwen3.6-27B (the "privileged evaluator" E+) is used ONLY for:
  → comparing rollout v̂ with ground-truth future v* to produce
    false_accept / false_reject binary labels.
  → These labels feed into the reward R+(τ_a):
       R+(τ_a) = 1[ŷ=y*] - λ_sim·N_sim - λ_FA·FA - λ_FR·FR

Qwen3.6-27B does NOT provide P_t+(a).
P_t+(a) comes from π_θ (the student model) with privileged inputs.

This is computed in stage2_pfopsd.py::get_student_priv_probs(), which
feeds c_t+ = c_t ∪ {v*, y*} through the student model and extracts
per-token logit probabilities for each candidate action.
"""

from __future__ import annotations

import base64
import json
import os
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from openai import OpenAI


# ─────────────────────────────────────────────────────────────────────────────
# Data classes
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class AttemptLabel:
    """
    Rollout quality label from Qwen3.6-27B (privileged evaluator E+).
    Used to compute false_accept / false_reject terms in R+(τ_a).
    """
    attempt_index:  int
    useful_rollout: bool   # True ↔ rollout consistent with v* and informative for q


@dataclass
class TrajectoryReward:
    """Full reward R+(τ_a) for one completed trajectory."""
    r_answer:       float
    r_sim_pen:      float
    r_fa_pen:       float
    r_fr_pen:       float
    total:          float
    attempt_labels: list[AttemptLabel] = field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────────────
# Prompt for E+ (Qwen3.6-27B) — rollout quality only
# ─────────────────────────────────────────────────────────────────────────────

_ROLLOUT_EVAL_PROMPT = """\
You are a PRIVILEGED EVALUATOR assessing world-model rollout quality.

IMAGE LAYOUT
  • Image 1          — ANCHOR FRAME (initial condition).
  • Images 2 – (R+1) — ROLLOUT FRAMES (v̂): generated by the world model.
  • Images (R+2) – N — FUTURE FRAMES (v*): the actual physical outcome.

TASK
Decide whether the rollout v̂ is useful for answering the question:

  useful_rollout: true  — rollout is broadly consistent with v* on the
                          task-relevant outcome AND would provide useful
                          concrete evidence for answering q.
  useful_rollout: false — rollout clearly contradicts v*, misses the key
                          interaction, or is physically implausible.

QUESTION: {question}
OPTIONS:
{options_text}
GROUND-TRUTH ANSWER (y*): {gt_answer}
ROLLOUT FRAMES: {n_rollout_frames}  (attempt index {attempt_index})

Return JSON only: {{"useful_rollout": true | false, "reasoning": "one sentence"}}
"""


# ─────────────────────────────────────────────────────────────────────────────
# PrivilegedEvaluator  (Qwen3.6-27B)
# ─────────────────────────────────────────────────────────────────────────────

class PrivilegedEvaluator:
    """
    Calls Qwen3.6-27B with privileged context (v*, y*) to assess whether
    a world-model rollout v̂ is consistent with the actual future v*.

    This is the ONLY role of the 27B model in PF-OPSD.
    P_t+(a) (the teacher-view action distribution) is NOT computed here —
    it is computed by the student model π_θ itself with privileged inputs
    (see get_student_priv_probs() in stage2_pfopsd.py).

    Parameters
    ----------
    model:    evaluator model name (paper: "Qwen3.6-27B")
    base_url: OpenAI-compatible API endpoint
    api_key:  auth token (falls back to $OPENAI_API_KEY)
    """

    def __init__(
        self,
        model:    str = "Qwen3.6-27B",
        base_url: str = os.environ.get("OPENAI_API_BASE", "https://api.openai.com/v1"),
        api_key:  str = "",
    ):
        self.model  = model
        self.client = OpenAI(
            api_key  = api_key or os.environ.get("OPENAI_API_KEY", ""),
            base_url = base_url,
        )

    def evaluate_attempt(
        self,
        anchor_path:    str,
        rollout_paths:  list[str],
        future_paths:   list[str],
        sample:         dict,
        attempt_index:  int,
        max_retries:    int = 2,
    ) -> Optional[AttemptLabel]:
        """
        Ask E+ (Qwen3.6-27B) whether rollout v̂ is consistent with v*.
        Returns AttemptLabel or None on repeated failure.

        Called once per simulation attempt per training example.
        Used to derive the false_accept and false_reject terms in R+(τ_a).
        """
        prompt = _ROLLOUT_EVAL_PROMPT.format(
            question         = sample["question"],
            options_text     = "\n".join(
                f"  {k}: {v}" for k, v in sample["options"].items()
            ),
            gt_answer        = sample["gt_answer"],
            n_rollout_frames = len(rollout_paths),
            attempt_index    = attempt_index,
        )
        all_imgs = [anchor_path] + rollout_paths + future_paths

        for attempt in range(max_retries):
            try:
                raw    = self._call(prompt, all_imgs)
                parsed = _parse_json(raw)
                if parsed and "useful_rollout" in parsed:
                    return AttemptLabel(
                        attempt_index  = attempt_index,
                        useful_rollout = bool(parsed["useful_rollout"]),
                    )
            except Exception:
                if attempt < max_retries - 1:
                    time.sleep(3)
        return None

    def evaluate_trajectory(
        self,
        trajectory:   dict,
        sample:       dict,
        future_paths: list[str],
        repo_root:    Path,
    ) -> tuple[TrajectoryReward, int, int, int]:
        """
        Compute R+(τ_a) components for one completed trajectory.
        Calls evaluate_attempt() for each simulation attempt.
        Returns (raw_reward, n_sim, fa_ind, fr_ind), where fa_ind/fr_ind are the
        trajectory-level false-accept / false-reject INDICATORS (each ∈ {0,1})
        matching the paper's 1[false accept] / 1[false reject] terms.
        """
        y_pred    = trajectory.get("y", "")
        gt_answer = sample["gt_answer"]
        attempts  = trajectory.get("simulation_attempts", [])

        r_answer  = 1.0 if y_pred == gt_answer else 0.0
        n_sim     = len(attempts)
        # Paper R+(τ_a) uses trajectory-level INDICATORS 1[false accept] and
        # 1[false reject] (each ∈ {0,1}), not per-attempt counts.
        fa_ind = fr_ind = 0
        labels: list[AttemptLabel] = []

        anchor_path = _resolve(sample["image_path"], repo_root)

        for att in attempts:
            z_ver       = att.get("z_ver", "uncertain")
            rollout_rel = att.get("rollout_frame_paths", [])
            rollout_abs = [
                _resolve(f, repo_root) for f in rollout_rel
                if Path(_resolve(f, repo_root)).exists()
            ]

            if not rollout_abs:
                labels.append(AttemptLabel(att.get("attempt_index", 0), False))
                continue

            label = self.evaluate_attempt(
                anchor_path   = anchor_path,
                rollout_paths = rollout_abs,
                future_paths  = future_paths,
                sample        = sample,
                attempt_index = att.get("attempt_index", 0),
            )
            if label is None:
                labels.append(AttemptLabel(att.get("attempt_index", 0), False))
                continue

            labels.append(label)
            if z_ver == "accept" and not label.useful_rollout:
                fa_ind = 1
            if z_ver == "reject" and label.useful_rollout:
                fr_ind = 1

        raw = TrajectoryReward(
            r_answer=r_answer, r_sim_pen=0., r_fa_pen=0.,
            r_fr_pen=0., total=0., attempt_labels=labels,
        )
        return raw, n_sim, fa_ind, fr_ind

    def _call(self, prompt: str, image_paths: list[str]) -> str:
        content: list[dict] = [{"type": "text", "text": prompt}]
        for p in image_paths:
            if not Path(p).exists():
                continue
            b64  = _encode_image(p)
            ext  = Path(p).suffix.lower().lstrip(".")
            mime = "image/jpeg" if ext in ("jpg", "jpeg") else "image/png"
            content.append({
                "type":      "image_url",
                "image_url": {"url": f"data:{mime};base64,{b64}"},
            })
        resp = self.client.chat.completions.create(
            model    = self.model,
            messages = [{"role": "user", "content": content}],
        )
        return resp.choices[0].message.content


# ─────────────────────────────────────────────────────────────────────────────
# Reward assembly
# ─────────────────────────────────────────────────────────────────────────────

def compute_reward(
    trajectory:   dict,
    sample:       dict,
    future_paths: list[str],
    evaluator:    PrivilegedEvaluator,
    repo_root:    Path,
    *,
    lambda_sim:   float = 0.05,
    lambda_fa:    float = 0.50,
    lambda_fr:    float = 0.25,
) -> TrajectoryReward:
    """
    R+(τ_a) = 1[ŷ=y*] - λ_sim·N_sim - λ_FA·1[false accept] - λ_FR·1[false reject]
    (paper Eq. 5).  N_sim is a count; the FA/FR terms are 0/1 indicators.
    """
    raw, n_sim, fa_ind, fr_ind = evaluator.evaluate_trajectory(
        trajectory, sample, future_paths, repo_root
    )
    r_sim_pen = -lambda_sim * n_sim
    r_fa_pen  = -lambda_fa  * fa_ind
    r_fr_pen  = -lambda_fr  * fr_ind
    total     = raw.r_answer + r_sim_pen + r_fa_pen + r_fr_pen

    return TrajectoryReward(
        r_answer       = raw.r_answer,
        r_sim_pen      = r_sim_pen,
        r_fa_pen       = r_fa_pen,
        r_fr_pen       = r_fr_pen,
        total          = total,
        attempt_labels = raw.attempt_labels,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _encode_image(path: str) -> str:
    with open(path, "rb") as fh:
        return base64.b64encode(fh.read()).decode("utf-8")


def _parse_json(text: str) -> dict | None:
    m = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    raw = m.group(1) if m else None
    if raw is None:
        m = re.search(r"(\{.*\})", text, re.DOTALL)
        raw = m.group(1) if m else text.strip()
    try:
        return json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        return None


def _resolve(rel: str, root: Path) -> str:
    p = Path(rel)
    return str(p) if p.is_absolute() else str(root / rel)
