#!/usr/bin/env python3
"""
stage1_sft.py
=============
Stage 1 of PF-OPSD: Protocol Supervised Fine-Tuning.

Trains the student MLLM on privileged teacher trajectories generated by
trajectory_gen/pipeline.py.  Built on **trl.SFTTrainer** (which itself
subclasses the HuggingFace Trainer) with LoRA (PEFT) and Accelerate for
multi-GPU support.  The on-policy generation / optimisation loop, gradient
accumulation, checkpointing and logging are delegated to trl.

Hyperparameters (from paper Appendix A):
    LoRA rank r=64, alpha=128
    Optimizer: AdamW, lr=5e-6, bfloat16
    Batch size: 32 (effective), max_length: 16384
    Epochs: 1
    Target modules: q_proj, k_proj, v_proj, o_proj, gate_proj, up_proj, down_proj

Usage
-----
    # Single-GPU debug:
    python -m train.stage1_sft --config train/configs/sft.yaml

    # Multi-GPU via Accelerate:
    accelerate launch --num_processes 4 -m train.stage1_sft \\
        --config train/configs/sft.yaml
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch
import yaml
from accelerate.utils import set_seed
from peft import LoraConfig, TaskType, get_peft_model
from torch.utils.data import random_split
from transformers import AutoProcessor, AutoModelForCausalLM
from trl import SFTConfig, SFTTrainer

from .dataset import SFTDataset, build_collate_fn

_REPO_ROOT = Path(__file__).resolve().parent.parent


# ─────────────────────────────────────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────────────────────────────────────

def _default_cfg() -> dict:
    return {
        # Model
        "model_name_or_path": "Qwen/Qwen3.5-9B",
        "attn_implementation": "flash_attention_2",
        # Data
        "trajectory_dir": "trajectory_gen/output/trajectories",
        "max_rollout_frames": 8,
        "d_sim_balance": 2.0,
        "val_fraction": 0.02,
        # Training
        "output_dir": "checkpoints/stage1_sft",
        "num_epochs": 1,
        "per_device_batch_size": 2,
        "gradient_accumulation_steps": 16,
        "max_length": 16384,
        "learning_rate": 5e-6,
        "warmup_ratio": 0.03,
        "weight_decay": 0.0,
        "max_grad_norm": 1.0,
        "seed": 42,
        "save_steps": 200,
        "log_steps": 10,
        # LoRA
        "lora_r": 64,
        "lora_alpha": 128,
        "lora_dropout": 0.05,
        "lora_target_modules": [
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
        ],
    }


def _load_cfg(config_path: str | None) -> dict:
    cfg = _default_cfg()
    if config_path and Path(config_path).exists():
        with open(config_path) as fh:
            override = yaml.safe_load(fh) or {}
        cfg.update(override)
    return cfg


# ─────────────────────────────────────────────────────────────────────────────
# Model loading
# ─────────────────────────────────────────────────────────────────────────────

def _load_model_and_processor(cfg: dict):
    """
    Load the Qwen3.5 VL model and processor.
    Applies LoRA adapters; freezes the visual encoder.

    Gradient checkpointing is NOT enabled here — it is configured through
    SFTConfig(gradient_checkpointing=True) so trl can attach the required
    input-require-grad hooks for the PEFT model.
    """
    model_path = cfg["model_name_or_path"]

    processor = AutoProcessor.from_pretrained(model_path, trust_remote_code=True)

    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        dtype               = torch.bfloat16,
        attn_implementation = cfg.get("attn_implementation", "sdpa"),
        trust_remote_code   = True,
    )

    # Freeze visual encoder if a standalone ViT exists.
    for name, param in model.named_parameters():
        if any(k in name for k in ("visual.", "vision_tower.", "patch_embed.")):
            param.requires_grad_(False)

    # Apply LoRA
    lora_cfg = LoraConfig(
        task_type        = TaskType.CAUSAL_LM,
        r                = cfg["lora_r"],
        lora_alpha       = cfg["lora_alpha"],
        lora_dropout     = cfg["lora_dropout"],
        target_modules   = cfg["lora_target_modules"],
        bias             = "none",
    )
    model = get_peft_model(model, lora_cfg)
    model.print_trainable_parameters()

    return model, processor


# ─────────────────────────────────────────────────────────────────────────────
# Training (trl.SFTTrainer)
# ─────────────────────────────────────────────────────────────────────────────

def train(cfg: dict) -> None:
    set_seed(cfg["seed"])

    output_dir = Path(cfg["output_dir"])
    if not output_dir.is_absolute():
        output_dir = _REPO_ROOT / output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    with open(output_dir / "config.json", "w") as fh:
        json.dump(cfg, fh, indent=2)

    # ── Data ──────────────────────────────────────────────────────────────
    traj_dir = _REPO_ROOT / cfg["trajectory_dir"]
    full_ds = SFTDataset(
        trajectory_dir     = traj_dir,
        repo_root          = _REPO_ROOT,
        max_rollout_frames = cfg["max_rollout_frames"],
        d_sim_balance      = cfg["d_sim_balance"],
        seed               = cfg["seed"],
    )

    n_val   = max(1, int(len(full_ds) * cfg["val_fraction"]))
    n_train = len(full_ds) - n_val
    train_ds, val_ds = random_split(
        full_ds, [n_train, n_val],
        generator=torch.Generator().manual_seed(cfg["seed"]),
    )
    print(f"[Data] train={len(train_ds)}  val={len(val_ds)}  total={len(full_ds)}")

    # ── Model + processor (LoRA applied) ───────────────────────────────────
    model, processor = _load_model_and_processor(cfg)
    collate_fn = build_collate_fn(processor, max_length=cfg["max_length"])

    # ── trl SFTConfig ──────────────────────────────────────────────────────
    # `skip_prepare_dataset` keeps our raw (image_paths/question_text/target_text)
    # samples untouched so our multimodal collate_fn does the tokenisation.
    args = SFTConfig(
        output_dir                  = str(output_dir),
        num_train_epochs            = cfg["num_epochs"],
        per_device_train_batch_size = cfg["per_device_batch_size"],
        per_device_eval_batch_size  = cfg["per_device_batch_size"],
        gradient_accumulation_steps = cfg["gradient_accumulation_steps"],
        learning_rate               = cfg["learning_rate"],
        lr_scheduler_type           = "cosine",
        warmup_ratio                = cfg["warmup_ratio"],
        weight_decay                = cfg["weight_decay"],
        adam_beta1                  = 0.9,
        adam_beta2                  = 0.95,
        adam_epsilon                = 1e-8,
        max_grad_norm               = cfg["max_grad_norm"],
        bf16                        = True,
        gradient_checkpointing      = True,
        logging_steps               = cfg["log_steps"],
        save_steps                  = cfg["save_steps"],
        save_strategy               = "steps",
        eval_strategy               = "epoch",
        seed                        = cfg["seed"],
        report_to                   = ["tensorboard"],
        remove_unused_columns       = False,
        dataset_kwargs              = {"skip_prepare_dataset": True},
    )

    trainer = SFTTrainer(
        model           = model,
        args            = args,
        train_dataset   = train_ds,
        eval_dataset    = val_ds,
        data_collator   = collate_fn,
        processing_class = processor,
    )

    trainer.train()

    # ── Final save ──────────────────────────────────────────────────────────
    final_dir = output_dir / "final"
    trainer.save_model(str(final_dir))
    processor.save_pretrained(str(final_dir))
    if trainer.is_world_process_zero():
        print(f"[Done] final model saved to {final_dir}")


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Stage 1 Protocol SFT for PF-OPSD (trl.SFTTrainer).",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--config", default="train/configs/sft.yaml",
                        help="Path to YAML config file.")
    parser.add_argument("--model_name_or_path",  default=None)
    parser.add_argument("--trajectory_dir",       default=None)
    parser.add_argument("--output_dir",           default=None)
    parser.add_argument("--num_epochs",           type=int,   default=None)
    parser.add_argument("--learning_rate",        type=float, default=None)
    parser.add_argument("--per_device_batch_size",type=int,   default=None)
    args = parser.parse_args()

    cfg = _load_cfg(args.config)
    # CLI overrides
    for k in ("model_name_or_path", "trajectory_dir", "output_dir",
              "num_epochs", "learning_rate", "per_device_batch_size"):
        v = getattr(args, k, None)
        if v is not None:
            cfg[k] = v

    train(cfg)


if __name__ == "__main__":
    main()
